sudo: required
services:
- docker
language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: buildmaster@rocket.chat
  on:
    tags: true
    all_branches: true
  skip_cleanup: true
  api_key:
    secure: X0o+l51cmU0W27heB6bXidC4kyfsLBwu4KbrSCaqyI/ffGbKCNPKGHwJqzOydgVKTYtdECjPC1dIstROj54vapmL4E5hDnP91PE09Kc1ft0DaCya6l8qg+loljEzB4dD2irRqexw2xQTy0GfjZlI6dcKUEJYLKl+5wTieRqDPp1p4s3rhqeAQ7qoTMPPyNkODffTL4f45qLaWMUtfMn4OH6XRj1uvVRUKFCOhYFewmLXUVD9//pPPH/Wbr293wTtPhVCR1N8ECEn7k1MgagYmLr4qYL6FWF+exXcbqoiobV/jPyyBp2+IpB/Jh6SRtHIXQUwQfJfs+skT5Ja5uuf6ACTaqrd+XK7i3Kd61ANzak2ljfpU345BHecLWUeNUsOfT2e19dWBNR59fkardMNEA4Br56GFEIz2ckxx2fHKUpc9PD1x0K7Kx//S1WOFezSIKLPAWL6saAcZVruTYUxi1OoXZkmPqUbTk786AuW53YsbgY1QeAFz7/08y7WXeUsEJDWa5PXFVE7ip8HX8mK/NcZ5G+T98gkUp/ZSqNioPQ5ac3a7s5IQMMwQ57D9lM33rPXnoTrEN4B1JMGJrtAaeQ06ruC50THNDlR5Tvw1ZuIWIPHvxIuv+teNeBtwZi5K+FcmmlHvcpnKMtQYEYXon9UbTZRWe/GPay4AEmF/Yk=
